<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Abdullah Faqih Al Mubarok">

<title>assignment8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="assignment8_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment8_files/libs/quarto-html/quarto.js"></script>
<script src="assignment8_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment8_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment8_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment8_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment8_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment8_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment8_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment8_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">assignment8</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Abdullah Faqih Al Mubarok </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Today’s exercises are based mainly on Chapter 9 in Wooldridge (2018). Some questions from previous chapters may also be included. In addition, the questions you may not have solved last week should be considered prerequisites to this exercise set. Feel free to post questions either by <a href="mailto:cep@ifro.ku.dk">mail</a> or the discussion forum <a href="https://ucph.padlet.org/carlemilpless/questions-ehvgql4yj517uhb3">here</a>. I will monitor both during the day and will be available for questions.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please remember that there is likely a large overlap between the contents of the readings, the smaller lectures and plenary sessions, and the videos I’ve provided. I do not expect you to spend <strong>time</strong> on all these different elements, but I expect you to choose whichever you learn the most from. In the end, the exercises are the ones that closest resemble what you can expect from the exam.</p>
</div>
</div>
<p>Unless stated otherwise, the primary source of data we will be using is from the <code>wooldridge</code> package. Remember, you can access them directly in <code>R</code> with the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>hprice1_data <span class="ot">&lt;-</span> hprice1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="problem-8.1-simulation-example" class="level2">
<h2 class="anchored" data-anchor-id="problem-8.1-simulation-example">Problem 8.1: Simulation Example</h2>
<p>First, we want to generate an artificial data set with 100 observations where: <span class="math display">\[\begin{align*}
    x&amp;\in[0,1] \\
    u&amp;\sim \mathcal{N}(0, 0.0025) \\
    y &amp;= 1 - x+2x^2 + u
\end{align*}\]</span> Using <code>R</code>, we can generate this artificial data set with the following snippet of code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nObs <span class="ot">=</span> <span class="dv">100</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="fu">runif</span>(nObs)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">=</span> <span class="fu">rnorm</span>(nObs, <span class="at">sd =</span> <span class="fl">0.0025</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> x <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> u</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>Estimate the linear model: <span class="math display">\[\begin{align*}
     y = \alpha_0 + \alpha_1 x + v,
\end{align*}\]</span> where <span class="math inline">\(v\)</span> is just some new error term with a zero conditional expectation.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>artif_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="st">"x"</span> <span class="ot">=</span> x, <span class="st">"u"</span> <span class="ot">=</span> u, <span class="st">"y_true"</span> <span class="ot">=</span> y)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>est_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> artif_data, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">formula =</span> y <span class="sc">~</span> x)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(est_model, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                                 y             
-----------------------------------------------
x                            0.993***          
                              (0.053)          
                                               
Constant                     0.664***          
                              (0.030)          
                                               
-----------------------------------------------
Observations                    100            
R2                             0.781           
Adjusted R2                    0.779           
Residual Std. Error       0.151 (df = 98)      
F Statistic           349.464*** (df = 1; 98)  
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>artif_data <span class="ot">&lt;-</span> artif_data <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"y_hat"</span> <span class="ot">=</span> est_model<span class="sc">$</span>fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Make a scatter plot between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> and add the estimated linear regression line.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> artif_data, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter Plot of Data"</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="assignment8_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="2" type="1">
<li>Make a scatter plot between <span class="math inline">\(x\)</span> and <span class="math inline">\(\hat{v}\)</span>. Recall that <span class="math inline">\(\hat{v}\)</span> are found by finding the estimated residuals of the linear model from 1.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>artif_data <span class="ot">&lt;-</span> artif_data <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">"u_hat"</span> <span class="ot">=</span> est_model<span class="sc">$</span>residuals)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> artif_data, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> u_hat)) <span class="sc">+</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">formula =</span> est_model<span class="sc">$</span>residuals <span class="sc">~</span> x, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatter Plot of Data"</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="assignment8_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that the x regress on u_hat is just a horizontal line</p>
<ol start="3" type="1">
<li><p>Which assumptions of the linear regression model are violated? for MLR.1 it is okay since our population model is linear MLR.2 is also okay since our samples are randomly picked from normal distribution MLR.3 is not violated since we have variation on x MLR.4 seems to be violated since the estimated residual depends on x (looks like a quadratic function) on the previous plot MLR.5 is violated because the variance is difference accross x.</p></li>
<li><p>How could you test whether or not these assumptions are fulfilled? FOr MLR.1 - 3 we don’t have to test them since it’s already stated on the problem set.</p></li>
</ol>
<p>However, to test the MLR.4 we can regress u_hat on x:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>u_hat_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> artif_data, </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> u_hat <span class="sc">~</span> x)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(u_hat_model, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                               u_hat           
-----------------------------------------------
x                             -0.000           
                              (0.053)          
                                               
Constant                       0.000           
                              (0.030)          
                                               
-----------------------------------------------
Observations                    100            
R2                             0.000           
Adjusted R2                   -0.010           
Residual Std. Error       0.151 (df = 98)      
F Statistic             0.000 (df = 1; 98)     
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>From the above result we can see that the coefficient on x is zero. However it is not statistically significant event at 10% level, hence we can’t reject the null which stated that the x coefficent is zero. However, it might be due to our model is not appropiate. We suspect that there is a quadratic relationship of x on u_hat. Therefore, we do another test for that:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>u_hat_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> artif_data, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> u_hat <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(u_hat_model, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                               u_hat           
-----------------------------------------------
x                            -1.997***         
                              (0.003)          
                                               
I(x2)                        2.004***          
                              (0.003)          
                                               
Constant                     0.336***          
                              (0.001)          
                                               
-----------------------------------------------
Observations                    100            
R2                             1.000           
Adjusted R2                    1.000           
Residual Std. Error       0.002 (df = 97)      
F Statistic         178,428.700*** (df = 2; 97)
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>From the above result, we can see that the association between u_hat and x is statistically significant. Hence, the assumption of MLR.3 does not hold.</p>
<p>For MLR.5 we can use BP test since homoskedasticity assume that E(x|u) = 0 (which is not as we prove above), therefore we can use any homoskedasticity test. Here we choose the BP test and using the F-test whether to reject or accept the null.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>bp_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> artif_data, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> <span class="fu">I</span>(u_hat<span class="sc">^</span><span class="dv">2</span>) <span class="sc">~</span> x)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(bp_model, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                             I(u_hat2)         
-----------------------------------------------
x                             -0.003           
                              (0.008)          
                                               
Constant                     0.024***          
                              (0.005)          
                                               
-----------------------------------------------
Observations                    100            
R2                             0.002           
Adjusted R2                   -0.009           
Residual Std. Error       0.024 (df = 98)      
F Statistic             0.163 (df = 1; 98)     
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>f_statistic <span class="ot">&lt;-</span> (<span class="fu">summary</span>(bp_model))<span class="sc">$</span>fstatistic[<span class="dv">1</span>]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"F-test result: "</span>, <span class="fu">pf</span>(f_statistic, <span class="dv">1</span>, <span class="dv">98</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-test result: 0.687374865888117"</code></pre>
</div>
</div>
<p>From the test above we can see that the F statistic is 2.529, which is statistically insignificant even at 10% level. Hence we can not reject the null hypothesis. Therefore, it might be that our sample is having heteroskedasticity.</p>
</section>
<section id="problem-8.2-functional-form-misspecification" class="level2">
<h2 class="anchored" data-anchor-id="problem-8.2-functional-form-misspecification">Problem 8.2: Functional Form Misspecification</h2>
<ol type="1">
<li>Using the data set <code>hprice1</code> from the <code>wooldridge</code> package, estimate the model: <span class="math display">\[\begin{align*}
     price = \beta_0 + \beta_1 lotsize + \beta_2 sqrft + \beta_3 bdrms + u,
\end{align*}\]</span> and carry out a test determining whether any quadratic terms should be included. To do that we can have restricted-F test where the restricted test is the model without the quadratif terms.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>hprice1_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> price <span class="sc">~</span> lotsize <span class="sc">+</span> sqrft <span class="sc">+</span> bdrms)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>hprice1_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> price <span class="sc">~</span> lotsize <span class="sc">+</span> <span class="fu">I</span>(lotsize<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> sqrft <span class="sc">+</span> <span class="fu">I</span>(sqrft<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> bdrms <span class="sc">+</span> <span class="fu">I</span>(bdrms<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(hprice1_model, hprice1_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: price ~ lotsize + sqrft + bdrms
Model 2: price ~ lotsize + I(lotsize^2) + sqrft + I(sqrft^2) + bdrms + 
    I(bdrms^2)
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     84 300724                                  
2     81 221823  3     78901 9.6038 1.703e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>From the restricted-F-test above, the p-value is statistically significant even at 1% level. thus, we can’t reject the null hypothesis which stated that all of the added coefficent are zero (there are quadratic relationship).</p>
<ol start="2" type="1">
<li>Instead, you should now estimate the model: <span class="math display">\[\begin{align*}
     \log(price) = \beta_0 + \beta_1 \log(lotsize) + \beta_2 \log(sqrft) + \beta_3 bdrms + u,
\end{align*}\]</span> where you again test whether any quadratic terms should be included. What about cubic terms or interactions? Again we do the same restricted f-test like we did before:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>hprice1_log_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> <span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(lotsize) <span class="sc">+</span> <span class="fu">log</span>(sqrft) <span class="sc">+</span> bdrms)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>hprice1_log_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> <span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(lotsize) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">log</span>(lotsize)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">log</span>(sqrft) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">log</span>(sqrft)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> bdrms <span class="sc">+</span> <span class="fu">I</span>(bdrms<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(hprice1_log_model, hprice1_log_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(price) ~ log(lotsize) + log(sqrft) + bdrms
Model 2: log(price) ~ log(lotsize) + I(log(lotsize)^2) + log(sqrft) + 
    I(log(sqrft)^2) + bdrms + I(bdrms^2)
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     84 2.8626                           
2     81 2.7001  3   0.16243 1.6242 0.1902</code></pre>
</div>
</div>
<p>Fomr the test result we can see that hte p-value is greater than our threshold (0.05). Hence, we can not reject the null hypothesis even at 10% level. Thus, the quadratic terms of the log() of explanatory variables should not be included.</p>
<p>For cubic terms:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>hprice1_log_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> <span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(lotsize) <span class="sc">+</span> <span class="fu">log</span>(sqrft) <span class="sc">+</span> bdrms)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>hprice1_log_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> <span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(lotsize) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">log</span>(lotsize)<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> <span class="fu">log</span>(sqrft) <span class="sc">+</span> <span class="fu">I</span>(<span class="fu">log</span>(sqrft)<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span> bdrms <span class="sc">+</span> <span class="fu">I</span>(bdrms<span class="sc">^</span><span class="dv">3</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(hprice1_log_model, hprice1_log_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(price) ~ log(lotsize) + log(sqrft) + bdrms
Model 2: log(price) ~ log(lotsize) + I(log(lotsize)^3) + log(sqrft) + 
    I(log(sqrft)^3) + bdrms + I(bdrms^3)
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     84 2.8626                           
2     81 2.7082  3   0.15438 1.5391 0.2107</code></pre>
</div>
</div>
<p>The cubic terms are also should not be included since the p-value of the restricted-F-test is greater than our threshold (0.05).</p>
<p>Finally for the interaction terms:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>hprice1_log_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> <span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(lotsize) <span class="sc">+</span> <span class="fu">log</span>(sqrft) <span class="sc">+</span> bdrms)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>hprice1_log_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> hprice1_data,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">formula =</span> <span class="fu">log</span>(price) <span class="sc">~</span> <span class="fu">log</span>(lotsize) <span class="sc">+</span> <span class="fu">log</span>(lotsize)<span class="sc">:</span><span class="fu">log</span>(sqrft) <span class="sc">+</span> <span class="fu">log</span>(sqrft) <span class="sc">+</span> <span class="fu">log</span>(sqrft)<span class="sc">:</span>bdrms <span class="sc">+</span> bdrms <span class="sc">+</span> bdrms<span class="sc">:</span><span class="fu">log</span>(lotsize))</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(hprice1_log_model, hprice1_log_model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: log(price) ~ log(lotsize) + log(sqrft) + bdrms
Model 2: log(price) ~ log(lotsize) + log(lotsize):log(sqrft) + log(sqrft) + 
    log(sqrft):bdrms + bdrms + bdrms:log(lotsize)
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     84 2.8626                           
2     81 2.6529  3   0.20966 2.1338 0.1023</code></pre>
</div>
</div>
<p>Also the same, for the interaction, we can’t reject the null hence we should not include the interaction term.</p>
<ol start="3" type="1">
<li>Apply Ramsey’s RESET (with squared and cubic fitted dependent variables) to the two models for housing prices from 1 and 2. What do you conclude? How do these results compare to your findings from 1 and 2?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(hprice1_model, <span class="at">power=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  hprice1_model
RESET = 9.3876, df1 = 1, df2 = 83, p-value = 0.002946</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(hprice1_log_model, <span class="at">power=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  hprice1_log_model
RESET = 5.122, df1 = 1, df2 = 83, p-value = 0.02623</code></pre>
</div>
</div>
<p>From the above result, for the quadratic explanatory variables we have the same results as we did previously where the non log() model can’t reject the null where all of the quadratic explanatory variables are zero. For the log() model we also see the same result as we did earlier where it is not a good idea to include the quadratic form into the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(hprice1_model, <span class="at">power=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  hprice1_model
RESET = 7.9123, df1 = 1, df2 = 83, p-value = 0.006127</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(hprice1_log_model, <span class="at">power=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  hprice1_log_model
RESET = 2.3601, df1 = 1, df2 = 83, p-value = 0.1283</code></pre>
</div>
</div>
<p>We also have the same result for the cubic.</p>
</section>
<section id="problem-8.3-proxy-variables" class="level2">
<h2 class="anchored" data-anchor-id="problem-8.3-proxy-variables">Problem 8.3: Proxy Variables</h2>
<ol type="1">
<li><p>What makes a good proxy variable? Throughout the course, we have discussed a wage model of the form: <span class="math display">\[\begin{align*}
     \log(wage) = \beta_0 + \beta_1 educ + \beta_2 exper + u,
\end{align*}\]</span> where one of the inherent problems was how we could measure general ability in the workplace. Would <span class="math inline">\(IQ\)</span> make for a good proxy of otherwise unobserved ability? Yes it will since generally the higher IQ someone has, the higher their ability since they can learn faster.</p></li>
<li><p>Now include <span class="math inline">\(IQ\)</span> in the above linear model. Estimate the model using the data in <code>wage2</code>. Report your results. How does this model compare to the restricted one from 1?</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>wage2_data <span class="ot">&lt;-</span> wage2</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>wage_model <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">data =</span> wage2_data, </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">formula =</span> <span class="fu">log</span>(wage) <span class="sc">~</span> educ <span class="sc">+</span> exper)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># assuming homoskedasticity, we use standard error </span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>se_wage_model <span class="ot">=</span> <span class="fu">vcov</span>(wage_model)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>proxy_wage_model <span class="ot">=</span> <span class="fu">lm</span>(<span class="at">data =</span> wage2_data, </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">formula =</span> <span class="fu">log</span>(wage) <span class="sc">~</span> educ <span class="sc">+</span> exper <span class="sc">+</span> IQ)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(wage_model, proxy_wage_model, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===================================================================
                                  Dependent variable:              
                    -----------------------------------------------
                                       log(wage)                   
                              (1)                     (2)          
-------------------------------------------------------------------
educ                       0.078***                0.057***        
                            (0.007)                 (0.007)        
                                                                   
exper                      0.020***                0.020***        
                            (0.003)                 (0.003)        
                                                                   
IQ                                                 0.006***        
                                                    (0.001)        
                                                                   
Constant                   5.503***                5.198***        
                            (0.112)                 (0.122)        
                                                                   
-------------------------------------------------------------------
Observations                  935                     935          
R2                           0.131                   0.162         
Adjusted R2                  0.129                   0.160         
Residual Std. Error    0.393 (df = 932)        0.386 (df = 931)    
F Statistic         70.162*** (df = 2; 932) 60.101*** (df = 3; 931)
===================================================================
Note:                                   *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>From the result above we could see that the IQ is statistically significant event at 1% level, hence we can reject that null hypotheses that IQ coeff is zero. In addition, we can also see that the coefficent value of education is smaller on the second estimation result. This is due to on the first estimation we excluded the IQ whic made our estimation is too high since we omitted ability (in this case IQ as the proxy). In addition, our R-squared is better.</p>
</section>
<section id="problem-8.4-outliers-and-influential-observations" class="level2">
<h2 class="anchored" data-anchor-id="problem-8.4-outliers-and-influential-observations">Problem 8.4: Outliers and Influential Observations</h2>
<p>Start by loading the data set <code>rdchem</code> from the <code>wooldridge</code> package.</p>
<ol type="1">
<li>Estimate the model <span class="math display">\[\begin{align*}
     rdintens = \beta_0 + \beta_1 sales + \beta_2 profmarg + u,
\end{align*}\]</span> and report your findings.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>rdchem_data <span class="ot">&lt;-</span> rdchem</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>rdchem_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> rdchem_data, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> rdintens <span class="sc">~</span> sales <span class="sc">+</span> profmarg)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(rdchem_model, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                             rdintens          
-----------------------------------------------
sales                         0.0001           
                             (0.00004)         
                                               
profmarg                       0.045           
                              (0.046)          
                                               
Constant                     2.625***          
                              (0.586)          
                                               
-----------------------------------------------
Observations                    32             
R2                             0.076           
Adjusted R2                    0.012           
Residual Std. Error       1.862 (df = 29)      
F Statistic             1.195 (df = 2; 29)     
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"F-test p-value: "</span>, <span class="fu">pf</span>(<span class="at">q =</span> <span class="fu">summary</span>(rdchem_model)<span class="sc">$</span>fstatistic[<span class="dv">1</span>], </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">df1 =</span> <span class="dv">2</span>, <span class="at">df2 =</span> <span class="dv">29</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-test p-value: 0.31727519984558"</code></pre>
</div>
</div>
<p>From the estimation result above we can see that the p-value of the f-test is 0.31 which is higher even at 10% significant level. Hence, we expect that sales and profmarg do not have effect on the percentage of between R&amp;D and sales.</p>
<ol start="2" type="1">
<li>Make a scatter plot of <span class="math inline">\(sales\)</span> and <span class="math inline">\(rdintens\)</span> and add the fitted values of <span class="math inline">\(rdintens\)</span> as a function of <span class="math inline">\(sales\)</span> to the plot. An outlier should appear (very large value of <span class="math inline">\(sales\)</span> compared to the other firms).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>rdchem_data <span class="ot">&lt;-</span> rdchem_data <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">fitted =</span> rdchem_model<span class="sc">$</span>fitted.values)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> rdchem_data, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> sales, <span class="at">y =</span> rdintens)) <span class="sc">+</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> fitted), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="assignment8_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the plot above we can se there are a company which has very high sales &gt;30000</p>
<ol start="3" type="1">
<li>Remove the observation that has an extreme value of <span class="math inline">\(sales\)</span>. Re-estimate the model from (i) and report your findings. Add the new fitted values of <span class="math inline">\(rdintens\)</span> as a function <span class="math inline">\(sales\)</span> to the plot from before.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>rdchem_model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> rdchem_data <span class="sc">|&gt;</span> <span class="fu">filter</span>(sales<span class="sc">&lt;=</span><span class="dv">30000</span>), </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> rdintens <span class="sc">~</span> sales <span class="sc">+</span> profmarg)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>rdchem_data_2 <span class="ot">&lt;-</span> rdchem_data <span class="sc">|&gt;</span> <span class="fu">filter</span>(sales<span class="sc">&lt;=</span><span class="dv">30000</span>) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">fitted =</span> rdchem_model2<span class="sc">$</span>fitted.values)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> rdchem_data_2, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> sales, <span class="at">y =</span> rdintens)) <span class="sc">+</span> </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> rdchem_data, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> fitted), </span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> fitted), </span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> rdchem_data, <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"blue"</span>, </span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="assignment8_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="4" type="1">
<li>Compare the estimated coefficients, <span class="math inline">\(R^2\)</span>-values, and the fitted values of the two models. Based on your findings, should we keep the observation with the extreme value of <span class="math inline">\(sales\)</span>, or should we discard it completely?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(rdchem_model, rdchem_model2, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
==========================================================
                             Dependent variable:          
                    --------------------------------------
                                   rdintens               
                           (1)                 (2)        
----------------------------------------------------------
sales                     0.0001            0.0002**      
                        (0.00004)           (0.0001)      
                                                          
profmarg                  0.045               0.048       
                         (0.046)             (0.044)      
                                                          
Constant                 2.625***           2.297***      
                         (0.586)             (0.592)      
                                                          
----------------------------------------------------------
Observations                32                 31         
R2                        0.076               0.173       
Adjusted R2               0.012               0.114       
Residual Std. Error  1.862 (df = 29)     1.792 (df = 28)  
F Statistic         1.195 (df = 2; 29) 2.925* (df = 2; 28)
==========================================================
Note:                          *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Based on the result above, we can see that the model with excluded outlier has better to fit the data with higher R-square. In addition, the sales is now statistically significant even at 1% level and also double the marginal effect. However, we still can see that despite it is better than the previous one, our model tends to poorly fit the data since it only explain 17.3% variability.</p>
<ol start="5" type="1">
<li>Can you come up with any other ways to deal with this issue? One idea to correct the issue is to revisit our model. Currently, we are only looking into the sales as well as the pformarg. However, we can easily see that the rdintens is highly correlated with rd (r&amp;d spending) as well as the sales. In addition, one big factor of a company can confidently do research is that they have enough cash which reflected from the net profit.<br>
Other than that, other thing that we can do is to transform several variables into log() especially variables which are in high amount of dollar. In addition, we can also test whether we need any quadratic correlation on the model is present.</li>
</ol>
<p>First we need to check whether transforming log(sales) give a better fit:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>rdchem_data <span class="ot">&lt;-</span> rdchem_data <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">lrd =</span> <span class="fu">log</span>(rd), <span class="at">lprofits =</span> <span class="fu">log</span>(profits))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `lprofits = log(profits)`.
Caused by warning in `log()`:
! NaNs produced</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>rdchem_model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> rdchem_data, </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> rdintens <span class="sc">~</span> lsales <span class="sc">+</span> lrd <span class="sc">+</span> profits)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>rechem_data3 <span class="ot">&lt;-</span> rdchem_data <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">fitted =</span> rdchem_model3<span class="sc">$</span>fitted.values)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(rdchem_model3, <span class="at">type =</span> <span class="st">"text"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===============================================
                        Dependent variable:    
                    ---------------------------
                             rdintens          
-----------------------------------------------
lsales                       -3.227***         
                              (0.230)          
                                               
lrd                          3.349***          
                              (0.206)          
                                               
profits                       -0.0002          
                             (0.0002)          
                                               
Constant                     14.399***         
                              (0.998)          
                                               
-----------------------------------------------
Observations                    32             
R2                             0.911           
Adjusted R2                    0.901           
Residual Std. Error       0.589 (df = 28)      
F Statistic           95.298*** (df = 3; 28)   
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"F-test p-value: "</span>, <span class="fu">pf</span>(<span class="at">q =</span> <span class="fu">summary</span>(rdchem_model3)<span class="sc">$</span>fstatistic[<span class="dv">1</span>], </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">df1 =</span> <span class="dv">2</span>, <span class="at">df2 =</span> <span class="dv">29</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-test p-value: 1.78326298830743e-13"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> rechem_data3, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> lsales, <span class="at">y =</span> rdintens)) <span class="sc">+</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">y =</span> fitted), </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"orange"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> rdchem_data, <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"orange"</span>, </span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="assignment8_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above result w can see that our model is now far way better to fit the data as we can see from the 0.911 R-square. All of the explanatory variables are statistically significant even at 1% level except for profit. This is not what we expected earlier. It might be due to profit has quadratic relation with rdintens. Therefore, we need to test it with RESET for possibly other quadratic relation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here we test whether there is any quadratic or cubic relationship </span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">resettest</span>(<span class="at">data =</span> rdchem_data, </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">formula =</span> rdintens <span class="sc">~</span> lsales <span class="sc">+</span> lrd <span class="sc">+</span> profits,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">power =</span> <span class="fu">c</span>(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    RESET test

data:  rdintens ~ lsales + lrd + profits
RESET = 719.59, df1 = 1, df2 = 27, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>from the result above, the p-value is very small which indicates that we can confidently reject the null. Therefore, it might be a quadratic relationship on our explanatory variables. I suspected that it is the profits. Therefore we need to do restricted F-test for it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>rdchem_model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> rdchem_data, </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">formula =</span> rdintens <span class="sc">~</span> lsales <span class="sc">+</span> lrd <span class="sc">+</span> profits <span class="sc">+</span> <span class="fu">I</span>(lsales<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(rdchem_model4, rdchem_model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: rdintens ~ lsales + lrd + profits + I(lsales^2)
Model 2: rdintens ~ lsales + lrd + profits
  Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
1     27 9.6785                           
2     28 9.7082 -1 -0.029706 0.0829 0.7756</code></pre>
</div>
</div>
<p>However, based on the above test the additional explanatory variable which is the sales^2 is not significant.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>